### ISSUE TITLE
Profiling PHP Applications with Xdebug (Rawkode Live)

### ISSUE THREAD

**Issue by piercemcgeough** [tighten/learn-xdebug#7]
https://www.youtube.com/watch?v=mNc_tcomrVs

In this episode, joined by Derick Rethans, we take a look at Xdebug and how it help you profile your PHP applications, allowing you to use a profiling front-end, like qcachegrind, to visualise your call graphs and dig into the bottlenecks of your applications.

Xdebug is an extension for PHP to assist with debugging and development.

- It contains a single step debugger to use with IDEs
- It upgrades PHP's var_dump() function
- It adds stack traces for Notices, Warnings, Errors and Exceptions
- It features functionality for recording every function call and variable assignment to disk
- It contains a profiler
- It provides code coverage functionality for use with PHPUnit

**Comment by derickr** [comment]
I approve ;-) 👍

**Comment by piercemcgeough** [comment]
@mattstauffer just after seeing the tags. Are you looking submitters to update the list in a PR? I'll do that if you want. I just thought it was lists to be submitted to the issues :)

**Comment by mattstauffer** [comment]
@piercemcgeough I'd love that! :)

**Comment by mattstauffer** [comment]
Closed by #9
